# Yarn 2+
image: node:lts

stages:
  - deploy



deploy:
  stage: deploy
  rules:
  - if: $CI_COMMIT_TAG
  before_script:
    - corepack enable
    - yarn set version stable
  script:
    - yarn npm publish
