# Yarn 2+
image: node:lts

variables:
  GIT_DEPTH: 1

cache: &global_cache
  paths:
    - node_modules/

stages:
  - deploy

deploy:
  stage: deploy
  cache:
    <<: *global_cache
  rules:
  - if: $CI_COMMIT_TAG
  before_script:
    - mv .yarnrc.yml.gitlab .yarnrc.yml
    - corepack enable
    - yarn set version self
    - yarn install
    - yarn build
  script:
    - yarn npm publish
