# Yarn 2+
image: node:lts

cache: &global_cache
  paths:
    - node_modules/

stages:
  - deploy

deploy:
  stage: deploy
  cache:
    <<: *global_cache
  rules:
  - if: $CI_COMMIT_TAG
  before_script:
    - corepack enable
#    - yarn set version stable
    - mv .yarnrc.yml.gitlab .yarnrn.yml
    - yarn install
    - yarn build
  script:
    - yarn npm publish
